### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#157]
![image](https://user-images.githubusercontent.com/717575/131650718-78392664-7d1b-4cac-8421-32f5ff7d5995.png)

а после ошибки не понятно, что делать дальше

![image](https://user-images.githubusercontent.com/717575/131650835-83e8ab8c-f147-4558-946c-6a3cb2ec8e40.png)

**Comment by HadronCollider** [comment]
@futurewarning 
```
172.21.0.1 - - [01/Sep/2021 10:03:29] "GET /upload HTTP/1.1" 200 -
	При обработке произошла ошибка: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/usr/src/project/app/servants/data.py", line 48, in upload
    check(parse(filename), checks, presentation_name, current_user.username)
  File "/usr/src/project/app/main/checker.py", line 95, in check
    checks.goals_slide, goals_array = __find_definite_slide(presentation, SLIDE_GOALS_AND_TASKS)
ValueError: too many values to unpack (expected 2)
```
